#define Buzeer_PIN         8
#define LED_BLUE_PIN       11
#define LED_RED_PIN        10
#define LED_GREEN_PIN      9
#define BUTTON_GREEN_PIN   12
#define BUTTON_BLUE_PIN    7
#define GREEN_LED_1        6
#define GREEN_LED_2        5
#define BLUE_LED_1         4
#define BLUE_LED_2         3
#define DELAY              100
#define WIN_COUNT          2
